### ISSUE TITLE
NINA 3.0 Ascom Framework

### ISSUE THREAD

**Issue by ASTRO1966** [brets-astro/sxascom-releases#3]
Hi Bret  have problem running my SX814 on NINA 3.0 . They are using a new Ascom framework .The CCD will take 3 exp then hang ran ok on Nina 2.3 
Here is log
2024-03-31T18:17:03.8570|INFO|SequenceItem.cs|Run|206|Starting Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 2x2
2024-03-31T18:17:03.8676|INFO|CameraVM.cs|Capture|724|Starting Exposure - Exposure Time: 1s; Filter: ; Gain: -1; Offset -1; Binning: 2x2;
2024-03-31T18:17:03.9217|INFO|SequenceItem.cs|Run|224|Finishing Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 2x2
2024-03-31T18:17:03.9218|INFO|SequenceItem.cs|Run|206|Starting Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-03-31T18:17:03.9220|WARNING|SequenceItem.cs|Run|251|Skipped Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-03-31T18:17:03.9221|INFO|SequenceItem.cs|Run|206|Starting Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 2x2
2024-03-31T18:17:03.9335|INFO|CameraVM.cs|Capture|724|Starting Exposure - Exposure Time: 1s; Filter: ; Gain: -1; Offset -1; Binning: 2x2;
2024-03-31T18:17:03.9562|ERROR|ImagingVM.cs|CaptureImage|264
ASCOM.InvalidOperationException: StartExposure called while in state cameraWaiting
   at ASCOM.Com.DriverAccess.DynamicAccess.CheckDotNetExceptions(String memberName, Exception e)
   at ASCOM.Com.DriverAccess.DynamicAccess.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure, CallSite, Object, Double, Boolean)
   at ASCOM.Com.DriverAccess.Camera.StartExposure(Double Duration, Boolean Light)
   at NINA.Equipment.Equipment.MyCamera.AscomCamera.StartExposure(CaptureSequence sequence) in C:\Projects\nina\NINA.Equipment\Equipment\MyCamera\AscomCamera.cs:line 673
   at NINA.WPF.Base.ViewModel.Equipment.Camera.CameraVM.Capture(CaptureSequence sequence, CancellationToken token, IProgress`1 progress)
   at NINA.ViewModel.ImagingVM.<>c__DisplayClass38_0.<<CaptureImage>b__0>d.MoveNext() in C:\Projects\nina\NINA\ViewModel\ImagingVM.cs:line 221
2024-03-31T18:17:03.9785|ERROR|SequenceItem.cs|Run|233|Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 2x2 - 
ASCOM.InvalidOperationException: StartExposure called while in state cameraWaiting
   at ASCOM.Com.DriverAccess.DynamicAccess.CheckDotNetExceptions(String memberName, Exception e)
   at ASCOM.Com.DriverAccess.DynamicAccess.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure, CallSite, Object, Double, Boolean)
   at ASCOM.Com.DriverAccess.Camera.StartExposure(Double Duration, Boolean Light)
   at NINA.Equipment.Equipment.MyCamera.AscomCamera.StartExposure(CaptureSequence sequence) in C:\Projects\nina\NINA.Equipment\Equipment\MyCamera\AscomCamera.cs:line 673
   at NINA.WPF.Base.ViewModel.Equipment.Camera.CameraVM.Capture(CaptureSequence sequence, CancellationToken token, IProgress`1 progress)
   at NINA.ViewModel.ImagingVM.<>c__DisplayClass38_0.<<CaptureImage>b__0>d.MoveNext() in C:\Projects\nina\NINA\ViewModel\ImagingVM.cs:line 221
--- End of stack trace from previous location ---
   at NINA.Sequencer.SequenceItem.Imaging.TakeExposure.Execute(IProgress`1 progress, CancellationToken token) in C:\Projects\nina\NINA.Sequencer\SequenceItem\Imaging\TakeExposure.cs:line 190
   at NINA.Sequencer.SequenceItem.SequenceItem.Run(IProgress`1 progress, CancellationToken token) in C:\Projects\nina\NINA.Sequencer\SequenceItem\SequenceItem.cs:line 222
Thanks karl

**Comment by bretmckee** [comment]
Karl:

I am sorry to hear you are having problems. 

The error is pretty clear: in ASCOM, exposures can only be started when the camera is in a state that allows them, and NINA requests an exposure when the camera is not in such a state. 

Could you also enable sxASCOM logging and send me both the sxASCOM and Nina logs for the imaging run?

They will show whether this is a sxASCOM or a NINA problem, and if it is a NINA problem, I'll report it to them using the data from the logs.

**Comment by ASTRO1966** [comment]
Hi Bret i am imaging tonight but with Nina 2.3  .Tomorrow i will install Nina 3.0 and run a dummy session during the day with logging on .
Thanks karl
________________________________

**Comment by ASTRO1966** [comment]
https://www.dropbox.com/scl/fi/5y7vchw0bs5j3altwlo5f/ASCOM.SXCamera.1426.357690.txt?rlkey=6dvm3a3b9kq2ibvqrtyrdq2u9&dl=0
[https://www.dropbox.com/static/metaserver/static/images/opengraph/opengraph-content-icon-file-text-landscape.png]<https://www.dropbox.com/scl/fi/5y7vchw0bs5j3altwlo5f/ASCOM.SXCamera.1426.357690.txt?rlkey=6dvm3a3b9kq2ibvqrtyrdq2u9&dl=0>
ASCOM.SXCamera.1426.357690.txt<https://www.dropbox.com/scl/fi/5y7vchw0bs5j3altwlo5f/ASCOM.SXCamera.1426.357690.txt?rlkey=6dvm3a3b9kq2ibvqrtyrdq2u9&dl=0>
Shared with Dropbox
www.dropbox.com
https://www.dropbox.com/scl/fi/3yn36s5azghb1rbbk61i9/ASCOM.SXCamera.1340.410840.txt?rlkey=b6libc73orcrp25r713llqg58&dl=0

https://www.dropbox.com/scl/fi/43trc4i9dkttqf3o0e2jr/ASCOM.SXCamera.1340.207150.txt?rlkey=kqasgjl8gttzvio5m12w29cqi&dl=0

https://www.dropbox.com/scl/fi/6qd65d2nrg9k9uwr4fxyo/20240408-133825-3.0.0.9001.15576-202404.log?rlkey=4tfj9qze8bfibnilg02bltnn2&dl=0
[https://www.dropbox.com/static/metaserver/static/images/opengraph/opengraph-content-icon-file-unknown-landscape.png]<https://www.dropbox.com/scl/fi/6qd65d2nrg9k9uwr4fxyo/20240408-133825-3.0.0.9001.15576-202404.log?rlkey=4tfj9qze8bfibnilg02bltnn2&dl=0>
20240408-133825-3.0.0.9001.15576-202404.log<https://www.dropbox.com/scl/fi/6qd65d2nrg9k9uwr4fxyo/20240408-133825-3.0.0.9001.15576-202404.log?rlkey=4tfj9qze8bfibnilg02bltnn2&dl=0>
Shared with Dropbox
www.dropbox.com

[https://www.dropbox.com/static/metaserver/static/images/opengraph/opengraph-content-icon-file-text-landscape.png]<https://www.dropbox.com/scl/fi/43trc4i9dkttqf3o0e2jr/ASCOM.SXCamera.1340.207150.txt?rlkey=kqasgjl8gttzvio5m12w29cqi&dl=0>
ASCOM.SXCamera.1340.207150.txt<https://www.dropbox.com/scl/fi/43trc4i9dkttqf3o0e2jr/ASCOM.SXCamera.1340.207150.txt?rlkey=kqasgjl8gttzvio5m12w29cqi&dl=0>
Shared with Dropbox
www.dropbox.com

________________________________

**Comment by bretmckee** [comment]
I finally got a chance to look at the logs. I see what Nina is doing, but the sxASCOM log time stamps don't seem to line up, so I can't see the interaction. Could you check the see if you have any other log files in the log directory for files that might cover 2024-04-08 @ 13:47

**Comment by bretmckee** [comment]
Note to self, here is what I found:

```# This sequence seems to be the problem.
2024-04-08T13:48:14.6440|INFO|SequenceItem.cs|Run|206|Starting Category: , Container: NINA.ViewModel.Sequencer.SimpleSequence.SimpleExposure, Strategy: SequentialStrategy, Items[CREATED]: 2, Conditions: Condition: LoopCondition, Iterations: 0/60, 

# Here is iteration 0 
2024-04-08T13:48:14.6441|INFO|SequenceItem.cs|Run|206|Starting Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:14.6442|WARNING|SequenceItem.cs|Run|251|Skipped Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:14.6443|INFO|SequenceItem.cs|Run|206|Starting Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 4x4
2024-04-08T13:48:14.6538|INFO|CameraVM.cs|Capture|724|Starting Exposure - Exposure Time: 1s; Filter: ; Gain: -1; Offset -1; Binning: 4x4;
# Notice that there is a ~3 second gap here for the image to be taken
2024-04-08T13:48:17.4128|INFO|SequenceItem.cs|Run|224|Finishing Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 4x4

# Here is iteration 1
2024-04-08T13:48:17.4131|INFO|SequenceItem.cs|Run|206|Starting Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:17.4133|WARNING|SequenceItem.cs|Run|251|Skipped Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:17.4133|INFO|SequenceItem.cs|Run|206|Starting Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 4x4
2024-04-08T13:48:17.4312|INFO|CameraVM.cs|Capture|724|Starting Exposure - Exposure Time: 1s; Filter: ; Gain: -1; Offset -1; Binning: 4x4;
# Notice that there is no gap here, so the camera is still exposing. 
# Race condition?  Maybe it is checking for the exposure to be done before it is starting?
2024-04-08T13:48:17.4391|INFO|SequenceItem.cs|Run|224|Finishing Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 4x4


# Here is iteration 2
2024-04-08T13:48:17.4392|INFO|SequenceItem.cs|Run|206|Starting Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:17.4394|WARNING|SequenceItem.cs|Run|251|Skipped Category: Filter Wheel, Item: SwitchFilter, Filter: 
2024-04-08T13:48:17.4394|INFO|SequenceItem.cs|Run|206|Starting Category: Camera, Item: TakeExposure, ExposureTime 1, Gain -1, Offset -1, ImageType LIGHT, Binning 4x4
2024-04-08T13:48:17.4559|INFO|CameraVM.cs|Capture|724|Starting Exposure - Exposure Time: 1s; Filter: ; Gain: -1; Offset -1; Binning: 4x4;
# When this exposure request is made, it fails because the previous exposure is
# still in progress.
2024-04-08T13:48:17.4636|ERROR|ImagingVM.cs|CaptureImage|264
ASCOM.InvalidOperationException: StartExposure called while in state cameraWaiting
   at ASCOM.Com.DriverAccess.DynamicAccess.CheckDotNetExceptions(String memberName, Exception e)
   at ASCOM.Com.DriverAccess.DynamicAccess.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure, CallSite, Object, Double, Boolean)
   at ASCOM.Com.DriverAccess.Camera.StartExposure(Double Duration, Boolean Light)
   at NINA.Equipment.Equipment.MyCamera.AscomCamera.StartExposure(CaptureSequence sequence) in C:\Projects\nina\NINA.Equipment\Equipment\MyCamera\AscomCamera.cs:line 676
   at NINA.WPF.Base.ViewModel.Equipment.Camera.CameraVM.Capture(CaptureSequence sequence, CancellationToken token, IProgress`1 progress)
   at NINA.ViewModel.ImagingVM.<>c__DisplayClass38_0.<<CaptureImage>b__0>d.MoveNext() in C:\Projects\nina\NINA\ViewModel\ImagingVM.cs:line 221

```

**Comment by ghost** [comment]
+1 for seeing this issue in NINA 3.0   I have a SX TRIUS 694 mono.  I degraded to 2.1 so as not to miss an imaging session but can go back if you need the logs but it may take a while

**Comment by ASTRO1966** [comment]
Hi Bret Nina and SX Ascom logs
https://www.dropbox.com/scl/fi/qrxadvi7ok4pijurkb85j/ASCOM.SXCamera.1426.357690.txt?rlkey=8ng9e8rclhkwefxz8aptv7nxn&st=dyzy9j39&dl=0

https://www.dropbox.com/scl/fi/cgf8mqd32u0wbuqpzs1bq/ASCOM.SXCamera.1340.410840.txt?rlkey=v2po2b5k4adcr4r4mnn3ntjmg&st=ld1jftau&dl=0

https://www.dropbox.com/scl/fi/mlajyp87gc6kwxdrfvzq5/ASCOM.SXCamera.1340.207150.txt?rlkey=a3rtqj0nh4ahfqbp1nbat8sby&st=w0u44ob7&dl=0

https://www.dropbox.com/scl/fi/vq5cawv1n7csx1wxmimdx/20240408-133825-3.0.0.9001.15576-202404.log?rlkey=ixph6a3yr3c3bwhmndo78bwr0&st=3ygkb0a0&dl=0
